apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.svc.name }}-{{ .Values.deployment.bluegreen }}"
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.appname }}   
    model_version: {{ .Values.deployment.bluegreen }}
  ports:
    - port: {{ .Values.svc.port }}
      targetPort: {{ .Values.deployment.container.port }}
      